### getwilds/rcromwell:v3.0.0
## Pull the R base image
FROM rocker/r-base:4.1.1
# Update
RUN apt-get update --fix-missing
RUN apt-get install -y libssl-dev libxml2-dev libcurl4-openssl-dev 
RUN apt-get install -y libssh-dev
# Install required packages
RUN R -e "install.packages('remotes', dependencies = TRUE)"
# Install from github
RUN R -e "remotes::install_github('getwilds/rcromwell@v3.0.0', dependencies = TRUE)"
# Override the R CMD for workflow managers
CMD ["/bin/bash"]
