# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "fullName", # <cromwell_cache_process>
  ".", # <cromwell_call>
  "fullName", # <cromwell_call>
  ".", # <cromwell_failures_process>
  "failures.message", # <cromwell_failures_process>
  "workflowMeta", # <cromwell_outputs_process>
  NULL
))
