# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "fullName", # <cromwell_cache>
  ".", # <cromwell_call>
  "fullName", # <cromwell_call>
  ".", # <cromwell_failures>
  "failures.message", # <cromwell_failures>
  "workflowMeta", # <cromwell_outputs>
  NULL
))
