# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "fullName", # <cromwellCache>
  ".", # <cromwellCall>
  "fullName", # <cromwellCall>
  ".", # <cromwellFailures>
  "failures.message", # <cromwellFailures>
  "workflowMeta", # <cromwellOutputs>
  NULL
))
